# Runs CI when pushing to develop branch
# runs pylint and pytest

name: CI_develop_action

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pylint pytest pytest-mock pytest-cov

    - name: Test with pytest
      run: |
        pytest --cov=cobra tests/

    # until we refactor accordingly
    #- name: Lint check with pylint
    #  run: |
    #    pylint cobra

    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
